name: Build And Deploy To Aliyun ECS

on:
  workflow_dispatch:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  Build-And-Deploy:
    name: build project
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.14.0'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Dependencies
        run: yarn install
      - name: Run Builder
        run: yarn build
      - name: Deploy To Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: '.output'
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          TARGET: 'instance/advance-myself'
